### ISSUE TITLE
Lineage Registration: plot or store the angle betwee cell division directions

### ISSUE THREAD

**Issue by maarzt** [mastodon-sc/mastodon-tomancak#24]
Currently the Lineage Registration plugin can be used to sort a TrackScheme and create tag sets. These output formats are useful, but the user does not get an idea how well the embryos are actually aligned. By computing and visualizing angles between matched cell division directions the user could get an understanding how well alignment works:
* 0 or 180 degree -> cell divisions directions are perfectly aligned, embryos develop very stereotypic. 
* 90 degrees -> cell division are poorly aligned, there is no indication of a stereotypic development.

The Lineage Registration Plugin should be extended to output angles between cell division directions. Output formats: as feature in Mastodon, as plot.

## Solution

* Ask @xulman  and @tinevez how computation results can be stored as a feature inside a Mastodon project. Is it somehow possible to circumvent the FeatureComputer. 
* The LineageRegistrationAlgorithm computes the scalar production between cell division directions. https://github.com/mastodon-sc/mastodon-tomancak/blob/fcd2d45880cd9be67a3e5ea4276625eee715a0af/src/main/java/org/mastodon/mamut/tomancak/lineage_registration/LineageRegistrationAlgorithm.java#L92. This scalar product could be used to compute angles between cell division. The code should be changed accordingly and the results should be stored as map (from Spot to double) in the LineageRegistrationResults.
* The LineageRegistrationDialog should get an additional button, to store the angles as Features in the Mastodon projects. There could also be a button to directly plot the angles over time.

**Comment by tinevez** [comment]
Hello @maarzt
I am not sure we have to workaround the feature framework totally. 
If I get it correctly, the cell division angle difference is a scalar numerical value that is associated to a cell division. If we can link it to an existing mastodon object then we can use a Feature to store the value. For instance it can be stored in a BranchVertex no?

Also, we don't have to use a FeatureComputer. We can have a generic Mastodon plugin that computes these values and store then in a Feature. Then declares the Feature to the FeatureModel. We just have to be careful about what we do when a branch vertex is deleted or added, but we should be fine.

**Comment by xulman** [comment]
( I think the discussion continued here: https://imagesc.zulipchat.com/#narrow/stream/327470-Mastodon/topic/Loading.20pre-computed.20feature.20in.20Mastodon )
