### ISSUE TITLE
tests failing on rev. 81bbd2b04b5a322b

### ISSUE THREAD

**Issue by xulman** [mastodon-sc/mastodon-tomancak#32]
![Screenshot_20230614_113453](https://github.com/mastodon-sc/mastodon-tomancak/assets/10509335/8451412d-bb0f-4786-b867-e7d1aa636f2d)

**Comment by maarzt** [comment]
This is a bug in mastodon-graph that is fixed with https://github.com/mastodon-sc/mastodon-graph/pull/14

**Comment by maarzt** [comment]
Fixed in 9b24d63f27e62f502c8690964b628f74c4652c99
