### ISSUE TITLE
TomancakLab Fiji update site need not provide grpc libs

### ISSUE THREAD

**Issue by xulman** [mastodon-sc/mastodon-tomancak#39]
Just noticed that [the official distribution of Fiji](https://fiji.sc/) comes with grpc libs pre-installed, ATM it ships v1.54. This is a new behaviour, I think.

Our Fiji update site ships grpc libs too, currently at v1.41.

After TomancakLab Fiji update site is enabled and its content is installed, the Fiji ends up with grpc libs at mixed versions, something is 1.54 and something is changed to 1.41; and the grpc downstream apps stop being functional (at least our Mastodon-to-Blender stuff breaks down).

I have tried to take a fresh Fiji installation with (grpc at v1.54), add the update site while making sure no grpc from the update site actually does install, and then tried to run our stuff and it worked well. So I think we no longer need to provide grpc libs as part of the update site and I propose we mark the grpc stuff obsolte/remove from the update site.

Are you okay with it? @maarzt  @stefanhahmann

**Comment by maarzt** [comment]
I remove the gRPC libraries from the tomancaklab update site. (Marked them as obsolete)
